   
apiVersion: batch/v1
kind: Job
	metadata:
		name: test-job
	spec:
		template:
			metadata:
				name: test-job
			spec:
				container:
				- name: test-job
				  image: python
				command:
				- python
				- test.py
				restartPolicy: OnFailure